name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: go-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.21.x', '1.22.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Go env
        run: go env

      - name: Tidy modules
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum || (echo "go.mod/go.sum changed after tidy; run 'go mod tidy' locally and commit" && exit 1)

      - name: Build
        run: go build ./...

      - name: Vet
        run: go vet ./...

      - name: Test (race, cover)
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.go-version }}.out
          path: coverage.out
          if-no-files-found: warn

